import axios from 'axios';
import { useEffect, useEffectEvent, useRef, useState } from 'react';

import { generateExecutionSummary } from '@/api/catalog';
import type { ExecutionSummaryResponseOut } from '@/types';

export const useExecutionSummary = (
  executionId: string,
  { autoGenerate = false }: { autoGenerate?: boolean } = {},
) => {
  const [data, setData] = useState<ExecutionSummaryResponseOut | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [requested, setRequested] = useState(false);
  const [elapsedMs, setElapsedMs] = useState(0);
  const [lastDurationMs, setLastDurationMs] = useState<number | null>(null);
  const [activeRequestStartedAt, setActiveRequestStartedAt] = useState<number | null>(null);
  const currentExecutionIdRef = useRef(executionId);
  const requestIdRef = useRef(0);
  const autoGeneratedExecutionIdRef = useRef<string | null>(null);

  useEffect(() => {
    currentExecutionIdRef.current = executionId;
    requestIdRef.current += 1;
    setData(null);
    setLoading(false);
    setError(null);
    setRequested(false);
    setElapsedMs(0);
    setLastDurationMs(null);
    setActiveRequestStartedAt(null);
    autoGeneratedExecutionIdRef.current = null;
  }, [executionId]);

  useEffect(() => {
    if (activeRequestStartedAt === null) {
      setElapsedMs(0);
      return;
    }

    const updateElapsed = () => {
      setElapsedMs(Date.now() - activeRequestStartedAt);
    };

    updateElapsed();
    const intervalId = window.setInterval(updateElapsed, 1000);

    return () => {
      window.clearInterval(intervalId);
    };
  }, [activeRequestStartedAt]);

  const generate = async () => {
    if (!executionId) return;

    const requestedExecutionId = executionId;
    const requestId = requestIdRef.current + 1;
    const startTime = Date.now();
    requestIdRef.current = requestId;
    const isLatestRequest = () =>
      requestId === requestIdRef.current &&
      currentExecutionIdRef.current === requestedExecutionId;

    setRequested(true);
    setLoading(true);
    setError(null);
    setElapsedMs(0);
    setLastDurationMs(null);
    setActiveRequestStartedAt(startTime);

    try {
      const result = await generateExecutionSummary(requestedExecutionId);
      if (!isLatestRequest()) {
        return;
      }
      setData(result);
    } catch (e) {
      if (!isLatestRequest()) {
        return;
      }
      setData(null);
      if (axios.isAxiosError(e) && (e.response?.status === 401 || e.response?.status === 403)) {
        setError('Log in to generate a summary for this execution.');
      } else {
        setError(e instanceof Error ? e.message : 'Failed to generate summary.');
      }
    } finally {
      if (isLatestRequest()) {
        setLastDurationMs(Date.now() - startTime);
        setActiveRequestStartedAt(null);
        setLoading(false);
      }
    }
  };

  const triggerAutoGenerate = useEffectEvent(() => {
    void generate();
  });

  useEffect(() => {
    if (
      !autoGenerate ||
      !executionId ||
      autoGeneratedExecutionIdRef.current === executionId ||
      loading ||
      requested
    ) {
      return;
    }

    autoGeneratedExecutionIdRef.current = executionId;
    triggerAutoGenerate();
    // eslint-disable-next-line react-hooks/exhaustive-deps -- Effect Events are intentionally excluded from dependency arrays.
  }, [autoGenerate, loading, requested, executionId]);

  return { data, loading, error, requested, elapsedMs, lastDurationMs, generate };
};
