import { TooltipTrigger } from '@radix-ui/react-tooltip';
import { Archive, ClipboardList, Copy, ExternalLink, FileText, Info, Package } from 'lucide-react';
import React, { JSX } from 'react';

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Tooltip, TooltipContent, TooltipProvider } from '@/components/ui/tooltip';

interface SimulationPathCard {
  kind: string;
  title: string;
  description?: string;
  paths?: string[] | { url: string; label: string }[];
  emptyText: string;
}

const titleIconMap: Record<string, JSX.Element> = {
  output: <Package size={16} />,
  archive: <Archive size={16} />,
  run_script: <FileText size={16} />,
  runScript: <FileText size={16} />,
  postprocessing_script: <ClipboardList size={16} />,
  batchLog: <ClipboardList size={16} />,
};

export const SimulationPathCard = ({
  kind,
  title,
  paths,
  emptyText,
  description,
}: SimulationPathCard) => {
  const hasPaths = paths && paths.length > 0;
  const copyPath = async (value: string) => {
    try {
      await navigator.clipboard.writeText(value);
    } catch {
      // Clipboard access is best-effort for local path convenience.
    }
  };

  const isExternalPath = (value: string) =>
    value.startsWith('http://') || value.startsWith('https://') || value.startsWith('file:');

  return (
    <Card
      className={
        hasPaths
          ? 'transition-colors hover:bg-accent/5'
          : 'bg-muted/40 border-dashed opacity-90 hover:opacity-100 transition-all hover:bg-accent/5'
      }
    >
      <CardHeader className="pb-2">
        <CardTitle
          className={`text-base flex items-center gap-2 ${hasPaths ? '' : 'text-muted-foreground'}`}
        >
          {React.cloneElement(titleIconMap[kind] || <></>, { size: 20 })}
          {title}
          {description && (
            <TooltipProvider delayDuration={100}>
              <Tooltip>
                <TooltipTrigger asChild>
                  <span
                    className="cursor-help text-muted-foreground align-middle"
                    title={description}
                  >
                    <Info size={14} strokeWidth={1.5} />
                  </span>
                </TooltipTrigger>
                <TooltipContent>{description}</TooltipContent>
              </Tooltip>
            </TooltipProvider>
          )}
        </CardTitle>
      </CardHeader>

      <CardContent className="space-y-2 text-sm">
        {hasPaths ? (
          <ul className="list-disc pl-5">
            {paths.map((path) => {
              const url = typeof path === 'string' ? path : path.url;
              const label = typeof path === 'string' ? path : path.label;
              return (
                <li key={url || label} className="flex items-start gap-2">
                  {isExternalPath(url) ? (
                    <a
                      className="text-blue-600 hover:underline flex items-center gap-1 break-all"
                      href={url}
                      target="_blank"
                      rel="noreferrer"
                    >
                      <ExternalLink size={16} className="inline-block shrink-0" />
                      {label}
                    </a>
                  ) : (
                    <div className="flex items-start gap-2 text-foreground">
                      <code className="break-all rounded bg-muted px-2 py-1 text-xs">{label}</code>
                      <button
                        type="button"
                        onClick={() => copyPath(url)}
                        className="rounded p-1 text-muted-foreground transition-colors hover:bg-muted hover:text-foreground"
                        aria-label="Copy path"
                        title="Copy full path"
                      >
                        <Copy size={14} />
                      </button>
                    </div>
                  )}
                </li>
              );
            })}
          </ul>
        ) : (
          <p className="text-muted-foreground italic flex items-center gap-1">
            {emptyText}
            <TooltipProvider delayDuration={100}>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Info size={14} strokeWidth={1.5} className="inline cursor-help align-middle" />
                </TooltipTrigger>
                <TooltipContent>
                  These files will be listed here if they are generated by the simulation or added
                  manually.
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>
          </p>
        )}
      </CardContent>
    </Card>
  );
};
