import type { ArtifactIn, ArtifactOut } from '@/types/artifact';
import type { ExternalLinkIn, ExternalLinkOut } from '@/types/link';
import type { Machine } from '@/types/machine';

export interface SimulationUserPreview {
  id: string;
  email: string;
  role: string;
  full_name?: string | null;
}

export type SimulationTypeValue = 'unknown' | 'production' | 'experimental' | 'test' | 'master';
export type SimulationStatusValue =
  | 'unknown'
  | 'created'
  | 'queued'
  | 'running'
  | 'failed'
  | 'completed';
export type ComputeType = 'cpu' | 'gpu';

export type SummaryCitationSourceType =
  | 'simulation_field'
  | 'case_field'
  | 'machine_field'
  | 'artifact'
  | 'external_link';

export interface SimulationSummaryCitationOut {
  sourceType: SummaryCitationSourceType;
  path: string;
  label: string;
}

export interface SimulationSummaryResponseOut {
  answer: string;
  citations: SimulationSummaryCitationOut[];
  assumptions: string[];
  caveats: string[];
  limitations: string[];
  suggestedFollowups: string[];
  generationMode?: 'llm' | 'deterministic';
  fallbackUsed?: boolean;
  generationProvider?: 'livai' | 'ollama' | null;
  generationModel?: string | null;
  traceId: string;
}

export interface SimulationSummaryCapabilitiesOut {
  llmAvailable: boolean;
  autoGenerateDeterministicOnLoad: boolean;
}

/**
 * Lightweight API response model for a Case with nested simulation summaries.
 */
export interface CaseSummaryOut {
  id: string;
  name: string;
  caseGroup: string | null;
  simulations: SimulationSummaryOut[];
  machineNames: string[];
  hpcUsernames: string[];
  links: ExternalLinkOut[];
  createdAt: string;
  updatedAt: string;
}

export interface CaseDetailOut extends CaseSummaryOut {
  description: string | null;
  keyFeatures: string | null;
  knownIssues: string | null;
  notesMarkdown: string | null;
}

export interface CaseListItemOut {
  id: string;
  name: string;
  caseGroup: string | null;
  machineId: string;
  machineName: string;
  hpcUsername: string;
  simulationCount: number;
  createdAt: string;
  updatedAt: string;
}

export interface PageOut<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}

export type CasePageOut = PageOut<CaseListItemOut>;

export interface FilterOptionOut {
  value: string;
  label: string;
}

export interface CatalogOverviewOut {
  totalCases: number;
  totalSimulations: number;
  latestSubmission: string | null;
  machineCounts: Record<string, number>;
  recentCases: CaseListItemOut[];
}

export interface CaseFilterOptionsOut {
  names: string[];
  caseGroups: string[];
  hpcUsernames: string[];
  machineIds: string[];
  machines: FilterOptionOut[];
  statuses: SimulationStatusValue[];
  simulationTypes: SimulationTypeValue[];
  campaigns: string[];
  initializationTypes: string[];
  compilers: string[];
  gitTags: string[];
  createdByIds: string[];
  creators: FilterOptionOut[];
}

export const CASE_EDITABLE_FIELDS = [
  'description',
  'keyFeatures',
  'knownIssues',
  'notesMarkdown',
] as const;

export type CaseEditableField = (typeof CASE_EDITABLE_FIELDS)[number];

export type CaseUpdate = Partial<Record<CaseEditableField, string | null>> & {
  links?: ExternalLinkIn[];
};

/**
 * Lightweight simulation summary for case-level nesting.
 * Does NOT include heavy relationships (machine, artifacts, links).
 */
export interface SimulationSummaryOut {
  id: string;
  executionId: string;
  caseHash: string | null;
  computeType: ComputeType | null;
  status: string;
  simulationStartDate: string;
  simulationEndDate: string | null;
}

/**
 * Request payload for creating a new simulation.
 * Equivalent to FastAPI SimulationCreate schema.
 */
export interface SimulationCreate {
  // Configuration
  // ~~~~~~~~~~~~~~
  caseId: string; // UUID
  executionId: string;
  caseHash?: string | null;
  description: string | null;
  compset: string;
  compsetAlias: string;
  gridName: string;
  gridResolution: string;

  // Model setup/context
  // ~~~~~~~~~~~~~~~~~~~
  simulationType: SimulationTypeValue;
  status: SimulationStatusValue;
  campaign?: string | null;
  experimentType?: string | null;
  initializationType: string;

  // Model timeline
  // ~~~~~~~~~~~~~~
  simulationStartDate: string; // ISO date (YYYY-MM-DD)
  simulationEndDate?: string | null; // ISO date (YYYY-MM-DD)
  runStartDate?: string | null;
  runEndDate?: string | null;
  compiler?: string | null;
  computeType?: ComputeType | null;

  // Metadata & audit
  // ~~~~~~~~~~~~~~~~~
  keyFeatures?: string | null;
  knownIssues?: string | null;
  notesMarkdown?: string | null;

  // Version control
  // ~~~~~~~~~~~~~~~
  gitRepositoryUrl?: string | null;
  gitBranch?: string | null;
  gitTag?: string | null;
  gitCommitHash?: string | null;

  // Provenance & submission
  // ~~~~~~~~~~~~~~~~~~~~~~~
  createdBy?: string | null;
  lastUpdatedBy?: string | null;

  // Miscellaneous
  // ~~~~~~~~~~~~~~~~~
  extra?: Record<string, unknown>;

  // Relationships
  // ~~~~~~~~~~~~~~
  artifacts: ArtifactIn[];
  links: ExternalLinkIn[];
}

export const SIMULATION_EDITABLE_FIELDS = [
  'simulationType',
  'status',
  'description',
  'campaign',
  'experimentType',
  'keyFeatures',
  'knownIssues',
  'notesMarkdown',
] as const;

export type SimulationEditableField = (typeof SIMULATION_EDITABLE_FIELDS)[number];

export interface SimulationUpdate extends Partial<Pick<SimulationCreate, SimulationEditableField>> {
  artifacts?: ArtifactIn[];
  links?: ExternalLinkIn[];
}

// UI-only create form shape. Extends API create payload with optional identity
// selectors and local path fields used during manual creation/import flows.
export interface SimulationCreateForm extends SimulationCreate {
  machineId?: string;
  hpcUsername?: string | null;
  outputPath?: string | null;
  archivePaths?: string[] | null;
  runScriptPaths?: string[] | null;
  postprocessingScriptPaths?: string[] | null;
}

/**
 * API response model for a simulation (from FastAPI / DB).
 * Equivalent to FastAPI SimulationOut schema.
 */
export interface SimulationOut extends SimulationCreate {
  // Configuration
  // ~~~~~~~~~~~~~~
  id: string;
  caseName: string;
  caseGroup: string | null;
  computeType: ComputeType | null;

  // Provenance & submission
  // ~~~~~~~~~~~~~~~~~~~~~~~
  machineId: string;
  hpcUsername?: string | null;
  createdAt: string; // Server-managed field
  updatedAt: string; // Server-managed field
  createdByUser?: SimulationUserPreview | null;
  lastUpdatedByUser?: SimulationUserPreview | null;

  // Relationships
  // ~~~~~~~~~~~~~~
  artifacts: ArtifactOut[];
  links: ExternalLinkOut[]; // merged simulation-owned + case-owned links, with ownerType metadata
  machine: Machine;

  // Computed fields
  // ~~~~~~~~~~~~~~~
  groupedArtifacts: Record<string, ArtifactOut[]>;
  groupedLinks: Record<string, ExternalLinkOut[]>;
  summaryCapabilities: SimulationSummaryCapabilitiesOut;
}

export interface SimulationListItemOut {
  id: string;
  caseId: string;
  caseName: string;
  caseGroup: string | null;
  executionId: string;
  caseHash: string | null;
  simulationType: SimulationTypeValue;
  status: SimulationStatusValue;
  campaign: string | null;
  experimentType: string | null;
  compset: string;
  compsetAlias: string;
  gridName: string;
  gridResolution: string;
  initializationType: string;
  simulationStartDate: string;
  simulationEndDate: string | null;
  runStartDate: string | null;
  runEndDate: string | null;
  compiler: string | null;
  computeType: ComputeType | null;
  gitBranch: string | null;
  gitTag: string | null;
  gitCommitHash: string | null;
  machineId: string;
  machineName: string;
  hpcUsername: string;
  createdBy: string | null;
  lastUpdatedBy: string | null;
  createdAt: string;
  updatedAt: string;
}

export type SimulationPageOut = PageOut<SimulationListItemOut>;

export interface SimulationFilterOptionsOut {
  caseNames: string[];
  caseGroups: string[];
  machineIds: string[];
  machines: FilterOptionOut[];
  hpcUsernames: string[];
  campaigns: string[];
  experimentTypes: string[];
  compsets: string[];
  gridNames: string[];
  gridResolutions: string[];
  simulationTypes: SimulationTypeValue[];
  initializationTypes: string[];
  compilers: string[];
  statuses: SimulationStatusValue[];
  gitTags: string[];
  createdByIds: string[];
  creators: FilterOptionOut[];
}
