import { useQueryClient } from '@tanstack/react-query';
import axios from 'axios';
import { useEffect, useState } from 'react';
import { useLocation, useParams } from 'react-router-dom';

import { resolvePaceExecution, updateExecution } from '@/api/catalog';
import { useAuth } from '@/auth/hooks/useAuth';
import {
  ExecutionDetailsView,
  type ExecutionSaveError,
} from '@/features/catalog/components/ExecutionDetailsView';
import { useExecutionSummary } from '@/features/catalog/hooks/useExecutionSummary';
import { useMetadataHistory } from '@/features/catalog/hooks/useMetadataHistory';
import { toast } from '@/hooks/use-toast';
import { useExecution } from '@/lib/catalog/hooks/useExecution';
import { invalidateCatalog } from '@/lib/catalog/invalidateCatalog';
import type { ExecutionOut, ExecutionUpdate } from '@/types';

const MAX_COMPARE_SELECTION = 5;

interface ExecutionDetailsPageProps {
  selectedExecutionIds: string[];
  setSelectedExecutionIds: (ids: string[]) => void;
}

const getUpdateError = (error: unknown): ExecutionSaveError => {
  if (axios.isAxiosError(error)) {
    const detail = error.response?.data?.detail;

    if (typeof detail === 'string') {
      return {
        message: detail,
        validationDetails: [],
      };
    }

    if (Array.isArray(detail)) {
      const validationDetails = detail
        .map((item) => {
          const message = typeof item?.msg === 'string' ? item.msg : null;
          const loc = Array.isArray(item?.loc)
            ? item.loc.filter(
                (part: unknown): part is string | number =>
                  typeof part === 'string' || typeof part === 'number',
              )
            : [];

          if (!message) return null;
          return {
            loc,
            msg: message,
          };
        })
        .filter((item): item is ExecutionSaveError['validationDetails'][number] => Boolean(item));

      if (validationDetails.length > 0) {
        return {
          message: 'One or more fields need attention before this execution can be saved.',
          validationDetails,
        };
      }
    }
  }

  return {
    message: error instanceof Error ? error.message : 'Failed to update execution.',
    validationDetails: [],
  };
};

export const ExecutionDetailsPage = ({
  selectedExecutionIds,
  setSelectedExecutionIds,
}: ExecutionDetailsPageProps) => {
  const queryClient = useQueryClient();
  const { id } = useParams<{ id: string }>();
  const location = useLocation();
  const { data: fetchedExecution, loading, error } = useExecution(id ?? '');
  const [isHistoryOpen, setIsHistoryOpen] = useState(false);
  const history = useMetadataHistory('execution', id ?? '', isHistoryOpen);
  const { user, isAuthenticated, loading: authLoading, loginWithGithub } = useAuth();
  const [execution, setExecution] = useState<ExecutionOut | null>(null);
  const [isSaving, setIsSaving] = useState(false);
  const [saveError, setSaveError] = useState<ExecutionSaveError | null>(null);
  const [paceExperimentId, setPaceExperimentId] = useState<string | null>(null);
  const [isResolvingPace, setIsResolvingPace] = useState(false);
  const [paceResolutionAttempted, setPaceResolutionAttempted] = useState(false);

  const state = location.state as { from?: string } | null;
  const backHref = typeof state?.from === 'string' ? state.from : '/browse';
  const normalizedBackHref = backHref.split(/[?#]/)[0];
  const backLabel = normalizedBackHref.startsWith('/cases/')
    ? 'Back to Case'
    : normalizedBackHref === '/cases'
      ? 'Back to Cases'
      : 'Back to Executions';
  const canEdit = !authLoading && user?.can_edit_managed_content === true;
  const currentExecution = execution?.id === id ? execution : null;
  const executionId = currentExecution?.executionId?.trim() ?? '';
  const llmSummaryAvailable = currentExecution?.summaryCapabilities?.llmAvailable ?? false;
  const shouldAutoGenerateSummary =
    currentExecution?.summaryCapabilities?.autoGenerateDeterministicOnLoad ?? false;
  const showLoginForAiSummary = llmSummaryAvailable && !authLoading && !isAuthenticated;
  const summary = useExecutionSummary(id ?? '', {
    autoGenerate: shouldAutoGenerateSummary,
  });

  useEffect(() => {
    if (fetchedExecution?.id === id) {
      setExecution(fetchedExecution);
      setSaveError(null);
      return;
    }

    if (!loading && !error) {
      setExecution(null);
    }
  }, [error, fetchedExecution, id, loading]);

  useEffect(() => {
    if (!executionId) {
      setPaceExperimentId(null);
      setIsResolvingPace(false);
      setPaceResolutionAttempted(false);
      return;
    }

    let cancelled = false;
    setPaceExperimentId(null);
    setIsResolvingPace(true);
    setPaceResolutionAttempted(false);

    resolvePaceExecution(executionId)
      .then((result) => {
        if (!cancelled) {
          setPaceExperimentId(result.experimentId?.trim() || null);
        }
      })
      .catch(() => {
        if (!cancelled) {
          setPaceExperimentId(null);
        }
      })
      .finally(() => {
        if (!cancelled) {
          setIsResolvingPace(false);
          setPaceResolutionAttempted(true);
        }
      });

    return () => {
      cancelled = true;
    };
  }, [executionId]);

  const handleSave = async (payload: ExecutionUpdate): Promise<boolean> => {
    if (!id) return false;

    setIsSaving(true);
    setSaveError(null);

    try {
      const updatedExecution = await updateExecution(id, payload);
      setExecution(updatedExecution);
      await invalidateCatalog(queryClient);
      await history.reset();
      return true;
    } catch (saveErr) {
      setSaveError(getUpdateError(saveErr));
      return false;
    } finally {
      setIsSaving(false);
    }
  };

  const handleToggleCompare = () => {
    if (!currentExecution) return;

    if (selectedExecutionIds.includes(currentExecution.id)) {
      setSelectedExecutionIds(
        selectedExecutionIds.filter((executionId) => executionId !== currentExecution.id),
      );
      return;
    }

    if (selectedExecutionIds.length >= MAX_COMPARE_SELECTION) {
      toast({
        title: 'Compare list full',
        description: `You can compare up to ${MAX_COMPARE_SELECTION} executions at a time.`,
        variant: 'destructive',
      });
      return;
    }

    setSelectedExecutionIds([...selectedExecutionIds, currentExecution.id]);
    toast({
      title: 'Added to compare',
      description: `${currentExecution.executionId} is now in your compare list.`,
    });
  };

  if (!id) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="text-center text-gray-500">Invalid execution ID</div>
      </div>
    );
  }

  if (loading || (execution !== null && currentExecution === null)) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="text-center text-gray-500">Loading execution details…</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="text-center text-red-600">Error: {error}</div>
      </div>
    );
  }

  if (!currentExecution) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="text-center text-gray-500">Execution not found</div>
      </div>
    );
  }

  const paceLink = executionId
    ? paceExperimentId
      ? {
          href: `https://pace.ornl.gov/exp-details/${encodeURIComponent(paceExperimentId)}`,
          label: 'Open in PACE',
        }
      : {
          href: `https://pace.ornl.gov/search/${encodeURIComponent(executionId)}`,
          label: 'Search in PACE',
        }
    : null;

  return (
    <ExecutionDetailsView
      execution={currentExecution}
      isCompareSelected={selectedExecutionIds.includes(currentExecution.id)}
      compareSelectionCount={selectedExecutionIds.length}
      maxCompareSelection={MAX_COMPARE_SELECTION}
      backHref={backHref}
      backLabel={backLabel}
      paceLink={paceLink}
      isResolvingPace={isResolvingPace}
      showPaceFallbackInfo={paceResolutionAttempted && !paceExperimentId}
      summary={summary.data}
      summaryLoading={summary.loading}
      summaryError={summary.error}
      summaryRequested={summary.requested}
      summaryElapsedMs={summary.elapsedMs}
      summaryLastDurationMs={summary.lastDurationMs}
      onGenerateSummary={summary.generate}
      canGenerateSummary
      onToggleCompare={handleToggleCompare}
      canEdit={canEdit}
      isAuthenticated={isAuthenticated}
      isSaving={isSaving}
      saveError={saveError}
      onSave={handleSave}
      onClearSaveError={() => setSaveError(null)}
      onLoginToEdit={loginWithGithub}
      llmSummaryAvailable={llmSummaryAvailable}
      autoGenerateDeterministicOnLoad={shouldAutoGenerateSummary}
      showLoginForAiSummary={showLoginForAiSummary}
      isCheckingAuth={authLoading && llmSummaryAvailable}
      onLoginForSummary={loginWithGithub}
      historyEntries={history.data}
      historyTotal={history.total}
      historyLoading={history.loading}
      historyLoadingMore={history.isFetchingNextPage}
      historyLoaded={history.loaded}
      historyError={history.error}
      historyCanLoadMore={history.hasNextPage}
      onHistoryLoadMore={() => void history.fetchNextPage()}
      onHistoryOpenChange={setIsHistoryOpen}
    />
  );
};
