"""Add description and key_feature fields to Simulation

Revision ID: a2cc72c91b71
Revises: 71f46a7e00a4
Create Date: 2025-10-07 14:27:31.861999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2cc72c91b71'
down_revision: Union[str, Sequence[str], None] = '71f46a7e00a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulations', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('simulations', sa.Column('key_features', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulations', 'key_features')
    op.drop_column('simulations', 'description')
    # ### end Alembic commands ###
