"""Remove _id from campaign and experimen_type

Revision ID: 1759fb9a80cc
Revises: 1134b6c8674f
Create Date: 2026-02-10 15:36:13.955474

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1759fb9a80cc"
down_revision: Union[str, Sequence[str], None] = "1134b6c8674f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("simulations", "campaign_id", new_column_name="campaign")
    op.alter_column(
        "simulations", "experiment_type_id", new_column_name="experiment_type"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("simulations", "campaign", new_column_name="campaign_id")
    op.alter_column(
        "simulations", "experiment_type", new_column_name="experiment_type_id"
    )
    # ### end Alembic commands ###
