"""Update DB schema for models.py changes

Revision ID: 3f4960b8c4ba
Revises: 0ac241ea9faf
Create Date: 2026-02-13 17:00:30.952323

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f4960b8c4ba"
down_revision: Union[str, Sequence[str], None] = "0ac241ea9faf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "simulations",
        "compset_alias",
        existing_type=sa.VARCHAR(length=120),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column(
        "simulations",
        "grid_name",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column(
        "simulations",
        "grid_resolution",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column(
        "simulations",
        "campaign",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "simulations",
        "experiment_type",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "simulations",
        "group_name",
        existing_type=sa.VARCHAR(length=120),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "simulations",
        "git_repository_url",
        existing_type=sa.VARCHAR(length=500),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "simulations",
        "git_repository_url",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=500),
        existing_nullable=True,
    )
    op.alter_column(
        "simulations",
        "group_name",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=120),
        existing_nullable=True,
    )
    op.alter_column(
        "simulations",
        "experiment_type",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "simulations",
        "campaign",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "simulations",
        "grid_resolution",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "simulations",
        "grid_name",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=200),
        existing_nullable=False,
    )
    op.alter_column(
        "simulations",
        "compset_alias",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=120),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
