"""Update simulation uniqueness constraint for deduplication

Revision ID: 4ab61b2fce04
Revises: 1759fb9a80cc
Create Date: 2026-02-12 11:36:49.693605

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4ab61b2fce04"
down_revision: Union[str, Sequence[str], None] = "1759fb9a80cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_simulation_name_tag", "simulations", type_="unique")
    op.drop_index("ix_simulations_case_name", table_name="simulations")
    op.create_index(
        op.f("ix_simulations_case_name"), "simulations", ["case_name"], unique=False
    )
    op.drop_index("ix_simulations_name", table_name="simulations")
    op.create_index(op.f("ix_simulations_name"), "simulations", ["name"], unique=False)
    op.create_unique_constraint(
        "uq_simulation_case_machine_date",
        "simulations",
        ["case_name", "machine_id", "simulation_start_date"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_simulation_case_machine_date", "simulations", type_="unique")
    op.drop_index(op.f("ix_simulations_name"), table_name="simulations")
    op.create_index("ix_simulations_name", "simulations", ["name"], unique=True)
    op.drop_index(op.f("ix_simulations_case_name"), table_name="simulations")
    op.create_index(
        "ix_simulations_case_name", "simulations", ["case_name"], unique=True
    )
    op.create_unique_constraint(
        "uq_simulation_name_tag",
        "simulations",
        ["name", "git_tag"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
