"""Add machine_id column to Ingestion table

Revision ID: 83737ddf5074
Revises: cf6f3dbad0e8
Create Date: 2026-02-18 11:18:11.172874

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "83737ddf5074"
down_revision: Union[str, Sequence[str], None] = "cf6f3dbad0e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ingestions", sa.Column("machine_id", sa.UUID(), nullable=False))
    op.create_index(
        op.f("ix_ingestions_machine_id"), "ingestions", ["machine_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_ingestions_machine_id_machines"),
        "ingestions",
        "machines",
        ["machine_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_ingestions_machine_id_machines"), "ingestions", type_="foreignkey"
    )
    op.drop_index(op.f("ix_ingestions_machine_id"), table_name="ingestions")
    op.drop_column("ingestions", "machine_id")
    # ### end Alembic commands ###
